### ISSUE TITLE
함수 호출량 적재를 위한 로깅 모듈 개발

### ISSUE THREAD

**Issue by geunho** [hypergamma/function-handler#1]
#### TODOs
- [x] nodejs용 influxdb 클라이언트 검토
- [x] sample program을 통한 검증
- [x] 모듈 개발

#### Features
- [x] 함수 호출 로깅
- [x] 함수 호출 실패 로깅
- [x] 사용자 코드 처리 시간 (ms)
사용자 코드 에러
데이터 소스에 대한 응답 지연 에러
그 외?

**Comment by geunho** [comment]
base project 가 어떤 프레임워크를 사용하냐에 따라 개발

**Comment by geunho** [comment]
expressjs. middleware로 작성할 것.

**Comment by geunho** [comment]
**함수 호출 로깅**
https://github.com/hypergamma/function-handler/pull/2

**Comment by geunho** [comment]
**함수 응답 시간 로깅**
https://github.com/hypergamma/function-handler/pull/3

**Comment by geunho** [comment]
핸들러에서 발생한 에러를 에러 코드로 세분화 하여 적재하면 좋겠지만 일단 마무리한다.
